image: mcr.microsoft.com/playwright:v1.57.0-jammy

stages:
  - test
  - report

cache:
  key: ${CI_COMMIT_REF_SLUG}-v2
  paths:
    - node_modules/

test_api:
  stage: test
  script:
    - npm ci
    - npx playwright test
  artifacts:
    when: always
    paths:
      - allure-results/
    expire_in: 1 day

pages:
  stage: report
  script:
    - apt-get update && apt-get install -y default-jre
    - npm ci
    - npm run report:generate
    - mkdir -p public
    - cp -r allure-report/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
